# Numpy

In [3]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)

#main function 
print(np.main())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
a = np.array([5,6,7])

In [ ]:
print(a)

In [ ]:
np.mean(arr)

In [ ]:
np.median(arr)

In [ ]:
np.std(arr)

In [ ]:
np.var(arr)


# 2.10 Array broadcasting in numpy

In [4]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0, 2.0, 2.0])

In [5]:
a*b

array([2., 4., 6.])

In [6]:
a+b

array([3., 4., 5.])

In [7]:
b/a

array([2.        , 1.        , 0.66666667])